# Jekyll v. 4.3.2, check out the Gemfile
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vega Checkout
description: >- # this means to ignore newlines until "baseurl:"
  Checkout de alta conversão para negócios digitais. Acesse grátis as ferramentas que você precisa para empreender na internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abrcoutinho.github.io/landing-vega" # the base hostname & protocol for your site, e.g. http://example.com

# Import SASS partials from sass_dir
sass:
  sass_dir: _sass
  style: compressed

# Links
signup: https://nova.vegacheckout.com.br/users/signup
login: https://nova.vegacheckout.com.br
legal: https://vegacheckout.com.br/use-terms-and-privacy-policy.html?v=7

